name: Build Check on Pull Request

on:
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Lint code
      run: npm run lint

    - name: Build application
      run: npm run build

    - name: Build summary
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Build completed successfully with Node.js ${{ matrix.node-version }}"
        else
          echo "❌ Build failed with Node.js ${{ matrix.node-version }}"
          exit 1
        fi
