name: Build Check

on:
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --silent

    - name: Generate Prisma Client
      run: npx prisma generate --silent

    - name: Build application
      run: npm run build

    - name: Build Summary
      if: success()
      run: |
        echo "###  Build Completed Successfully!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo " Your application is ready for production!" >> $GITHUB_STEP_SUMMARY
        
    - name:  Build Failed
      if: failure()
      run: |
        echo "### Build Failed " >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Please check the logs above for build errors." >> $GITHUB_STEP_SUMMARY
